services:
  user-db:
    image: postgres:16
    container_name: user-db
    environment:
      POSTGRES_USER: user_service
      POSTGRES_PASSWORD: devpassword
      POSTGRES_DB: user_db
    ports:
      - "5432:5432"
    volumes:
      - user_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user_service -d user_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  order-db:
    image: postgres:16
    container_name: order-db
    environment:
      POSTGRES_USER: order_service
      POSTGRES_PASSWORD: devpassword
      POSTGRES_DB: order_db
    ports:
      - "5433:5432"
    volumes:
      - order_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U order_service -d order_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  payment-db:
    image: postgres:16
    container_name: payment-db
    environment:
      POSTGRES_USER: payment_service
      POSTGRES_PASSWORD: devpassword
      POSTGRES_DB: payment_db
    ports:
      - "5434:5432"
    volumes:
      - payment_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U payment_service -d payment_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  dynamodb-local:
    image: amazon/dynamodb-local
    container_name: dynamodb-local
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal"
    ports:
      - "8000:8000"
    volumes:
      - dynamodb_data:/home/dynamodblocal

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"

  user-service:
    build: ./services/user-service
    container_name: user-service
    ports:
      - "8001:8000"
    environment:
      DATABASE_URL: postgresql://user_service:devpassword@user-db:5432/user_db
    volumes:
      - ./services/user-service/keys:/app/keys
    depends_on:
      user-db:
        condition: service_healthy

  product-service:
    build: ./services/product-service
    container_name: product-service
    ports:
      - "8002:8000"
    environment:
      DYNAMODB_ENDPOINT: http://dynamodb-local:8000
      REDIS_HOST: redis
    volumes:
      - ./services/product-service/keys:/app/keys
    depends_on:
      - dynamodb-local
      - redis

  inventory-service:
    build: ./services/inventory-service
    container_name: inventory-service
    ports:
      - "8003:8000"
    environment:
      DYNAMODB_ENDPOINT: http://dynamodb-local:8000
    volumes:
      - ./services/inventory-service/keys:/app/keys
    depends_on:
      - dynamodb-local
      
volumes:
  user_db_data:
  order_db_data:
  payment_db_data:
  dynamodb_data:

